steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build',
           '--build-arg',
           'node_version=${_NODE_VERSION_1}',
           '-t',
           'gcr.io/$PROJECT_ID/build-substitutions-nodejs-${_NODE_VERSION_1}',
           '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build',
           '--build-arg',
           'node_version=${_NODE_VERSION_2}',
           '-t',
           'gcr.io/$PROJECT_ID/build-substitutions-nodejs-${_NODE_VERSION_2}',
           '.']
substitutions:
  _NODE_VERSION_1: v6.9.1 # default value
  _NODE_VERSION_2: v6.9.2 # default value
images: [
    'gcr.io/$PROJECT_ID/build-substitutions-nodejs-${_NODE_VERSION_1}',
    'gcr.io/$PROJECT_ID/build-substitutions-nodejs-${_NODE_VERSION_2}'
]

# gcloud builds submit --config=cloudbuild.yaml --substitutions=_NODE_VERSION_1="v6.9.4",_NODE_VERSION_2="v6.9.5" .
