steps:
- name: 'gcr.io/my-project/pulumi'
  args:
    - 'run'
    - 'deploy'
    - 'cloudrunservice-sagtest-community'
    - '--image'
    - 'us-docker.pkg.dev/cloudrun/container/hello'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
