steps:
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "gcr.io/$PROJECT_ID/cb-demo-img", "."]
images:
  - gcr.io/$PROJECT_ID/cb-demo-img


# Usage
# gcloud builds submit --config=cloudbuild.yaml --substitutions=$PROJECT_ID="my-project"
